wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.2
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.5.6
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      4: 3.5.6
      5: 0.11.2
      8:
      - 5
batch_size:
  desc: null
  value: 1
epochs:
  desc: null
  value: 100
