wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1638848814
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 16
      4: 3.6.13
      5: 0.12.7
      8:
      - 5
batch_size:
  desc: null
  value: 1
epochs:
  desc: null
  value: 50
